server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        group: DEFAULT_GROUP
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: book
          uri: lb://book
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix=1
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=1
        - id: address
          uri: lb://address
          predicates:
            - Path=/api/address/**
          filters:
            - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
